# Site settings
title: 
email: andreleithnyc@gmail.com
url: https://dreLT.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: 
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/andreleith
  - title: github
    url: https://github.com/dreLT

# Postal address (add as many lines as necessary)
address:
  - line: andreleithnyc@gmail.com

# Credits content
credits: 

# Build settings
markdown: kramdown
permalink: pretty
